### ISSUE TITLE
I have some problem

### ISSUE THREAD

**Issue by readingbook78** [fedebotu/k-trains#4]
when I run your program, I had some problem that below.
Can you help me?

Error:
Traceback (most recent call last):
  File "C:\startcoding\k-trains-main\reserve.py", line 68, in get_trains
    email_sender = st.secrets.get("email_sender")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 774, in get
  File "C:\Users\anhur\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\anhur\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\secrets.py", line 214, in _parse
    raise FileNotFoundError(err_msg)
FileNotFoundError: No secrets files found. Valid paths for a secrets.toml file are: C:\Users\anhur\.streamlit\secrets.toml, C:\startcoding\k-trains-main\.streamlit\secrets.toml

**Comment by fedebotu** [comment]
Hi @readingbook78 , thanks for dropping by. That is correct, you need a `secrets.toml` file containing some info like user and password of your email account. Otherwise, you may want to modify the app to your needs (especially the notification function).

I added a small guide [here](https://github.com/fedebotu/k-trains#secrets-and-email-api-connection) ;)
